import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { AdjustmentStatus, StockMovementReasonCode } from '@skydrop/db';
import {
  ArrayMinSize,
  IsArray,
  IsEnum,
  IsIn,
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  Min,
  ValidateNested,
} from 'class-validator';

/** Manual adjustments are INCREASE or DECREASE only (TRANSFER is Phase 2;
 *  CYCLE_COUNT is generated by the cycle-count flow, not this endpoint). */
export type ManualAdjustmentType = 'INCREASE' | 'DECREASE';

export class AdjustmentLineDto {
  @ApiProperty()
  @IsUUID('7')
  variantId!: string;

  @ApiProperty()
  @IsUUID('7')
  binId!: string;

  @ApiProperty({
    description: 'Concrete batch the change applies to (required to locate the stock level)',
  })
  @IsUUID('7')
  batchId!: string;

  @ApiProperty({
    description: 'Signed delta; sign MUST match the adjustment type (INCREASE>0, DECREASE<0)',
  })
  @Type(() => Number)
  @IsInt()
  qtyChange!: number;

  @ApiProperty({
    required: false,
    minimum: 0,
    description: 'Overrides batch.unitCostInr for value impact',
  })
  @IsOptional()
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  unitCostInr?: number;
}

export class CreateStockAdjustmentDto {
  @ApiProperty()
  @IsUUID('7')
  sellerId!: string;

  @ApiProperty({ required: false, description: 'Defaults to the configured default warehouse' })
  @IsOptional()
  @IsUUID('7')
  warehouseId?: string;

  @ApiProperty({ enum: ['INCREASE', 'DECREASE'] })
  @IsIn(['INCREASE', 'DECREASE'])
  type!: ManualAdjustmentType;

  @ApiProperty({ enum: StockMovementReasonCode })
  @IsEnum(StockMovementReasonCode)
  reasonCode!: StockMovementReasonCode;

  @ApiProperty({ required: false, maxLength: 2000 })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  description?: string;

  @ApiProperty({ required: false, type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  photoSpacesKeys?: string[];

  @ApiProperty({ type: [AdjustmentLineDto], minItems: 1 })
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => AdjustmentLineDto)
  lines!: AdjustmentLineDto[];
}

export class ListStockAdjustmentsQueryDto {
  @ApiProperty({ required: false })
  @IsOptional()
  @IsUUID('7')
  sellerId?: string;

  @ApiProperty({ required: false })
  @IsOptional()
  @IsUUID('7')
  warehouseId?: string;

  @ApiProperty({ required: false, enum: AdjustmentStatus })
  @IsOptional()
  @IsEnum(AdjustmentStatus)
  status?: AdjustmentStatus;

  @ApiProperty({ required: false, default: 1, minimum: 1 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  page?: number;

  @ApiProperty({ required: false, default: 20, minimum: 1 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  pageSize?: number;
}

export class RejectAdjustmentDto {
  @ApiProperty({ maxLength: 2000 })
  @IsString()
  @MaxLength(2000)
  reason!: string;
}
