import { chromium } from '@playwright/test';
const base = 'http://127.0.0.1:3003';
const out = process.argv[2] ?? '/tmp/req.png';
const route = process.argv[3] ?? '/orders';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1920, height: 1080 }, colorScheme: 'dark', locale: 'en-IN', timezoneId: 'Asia/Dhaka' });
const page = await ctx.newPage();
await page.goto(`${base}/login`, { waitUntil: 'domcontentloaded' });
await page.getByLabel(/email/i).first().fill('demo@rangpursilk.test');
await page.getByLabel(/password/i).first().fill('Skydrop-Demo-2026');
await page.getByRole('button', { name: /sign in|log in/i }).first().click();
await page.waitForURL(/\/dashboard/, { timeout: 30000 });
await page.goto(`${base}${route}`, { waitUntil: 'domcontentloaded' });
await page.waitForLoadState('networkidle').catch(()=>{});
await page.waitForTimeout(3000);
await page.screenshot({ path: out, fullPage: true });
console.log((await page.locator('body').innerText()).slice(0, 5000));
await ctx.close(); await browser.close();
